name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # 使用默认的GITHUB_TOKEN来检出代码
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git User Information
        run: |
          git config user.name "Grovin720-bot[bot]"
          git config user.email "your-email@example.com"

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Update Internal Playlists
        run: npm run playlist:update --silent >> $GITHUB_OUTPUT
        id: playlist-update

      - name: Check Internal Playlists
        run: |
          npm run playlist:lint
          npm run playlist:validate

      - name: Generate Public Playlists
        run: npm run playlist:generate

      - name: Generate .api/streams.json
        run: npm run api:generate

      - name: Update README.md
        run: npm run readme:update

      - name: Add and Commit Changes to /streams
        run: |
          git add streams
          git commit --allow-empty -m "[Bot] Update /streams" -m "Committed by [Grovin720-bot](https://github.com/apps/Grovin720-bot) via [update](https://github.com/Grovin720/iptv-1/actions/runs/${{ github.run_id }}) workflow." -m "${{ steps.playlist-update.outputs.OUTPUT }}" --no-verify

      - name: Add and Commit Changes to README.md
        run: |
          git add README.md
          git commit --allow-empty -m "[Bot] Update README.md" -m "Committed by [Grovin720-bot](https://github.com/apps/Grovin720-bot) via [update](https://github.com/Grovin720/iptv-1/actions/runs/${{ github.run_id }}) workflow." --no-verify

      - name: Push All Changes to the Repository
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git push

      - name: Deploy Public Playlists to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repository-name: Grovin720/iptv-1
          branch: gh-pages
          folder: .gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: Grovin720-bot[bot]
          git-config-email: your-email@example.com
          commit-message: '[Bot] Deploy to GitHub Pages'
          clean: true

      - name: Move .api/streams.json to Grovin720/api (如果适用)
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
        with:
          repository-name: Grovin720/api
          branch: gh-pages
          folder: .api
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: Grovin720-bot[bot]
          git-config-email: your-email@example.com
          clean: false
